version: '3'
services:
    nginx:
        image: nginx
        restart: always
        ports:
            - 8000:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./frontend/dist:/home/web
    app-pm2:
        container_name: app-pm2
        build: ./backend
        ports:
            - 3000:3000
        